
package com.dsfy.refund;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebFault(name = "MasAPIException", targetNamespace = "http://www.sdo.com/mas/api/refund/")
public class MasAPIException_Exception extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private MasAPIException faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public MasAPIException_Exception(String message, MasAPIException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MasAPIException_Exception(String message, MasAPIException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: com.dsfy.refund.MasAPIException
     */
    public MasAPIException getFaultInfo() {
        return faultInfo;
    }

}
