
package com.dsfy.refund;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "RefundAPI", targetNamespace = "http://www.sdo.com/mas/api/refund/")
@XmlSeeAlso({ObjectFactory.class})
public interface RefundAPI {


    /**
     * @param arg0
     * @return returns com.dsfy.refund.RefundResponse
     * @throws MasAPIException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processRefund", targetNamespace = "http://www.sdo.com/mas/api/refund/", className = "com.dsfy.refund.ProcessRefund")
    @ResponseWrapper(localName = "processRefundResponse", targetNamespace = "http://www.sdo.com/mas/api/refund/", className = "com.dsfy.refund.ProcessRefundResponse")
    public RefundResponse processRefund(@WebParam(name = "arg0", targetNamespace = "") RefundRequest arg0) throws MasAPIException_Exception;
}
