
package com.dsfy.refund;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "RefundAPIExporterService", targetNamespace = "http://www.sdo.com/mas/api/refund/", wsdlLocation = "https://mas.shengpay.com/api-acquire-channel/services/refundService?wsdl")
public class RefundAPIExporterService extends Service {

    private final static URL REFUNDAPIEXPORTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException REFUNDAPIEXPORTERSERVICE_EXCEPTION;
    private final static QName REFUNDAPIEXPORTERSERVICE_QNAME = new QName("http://www.sdo.com/mas/api/refund/", "RefundAPIExporterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://mas.shengpay.com/api-acquire-channel/services/refundService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REFUNDAPIEXPORTERSERVICE_WSDL_LOCATION = url;
        REFUNDAPIEXPORTERSERVICE_EXCEPTION = e;
    }

    public RefundAPIExporterService() {
        super(__getWsdlLocation(), REFUNDAPIEXPORTERSERVICE_QNAME);
    }

    public RefundAPIExporterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REFUNDAPIEXPORTERSERVICE_QNAME, features);
    }

    public RefundAPIExporterService(URL wsdlLocation) {
        super(wsdlLocation, REFUNDAPIEXPORTERSERVICE_QNAME);
    }

    public RefundAPIExporterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REFUNDAPIEXPORTERSERVICE_QNAME, features);
    }

    public RefundAPIExporterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RefundAPIExporterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns RefundAPI
     */
    @WebEndpoint(name = "RefundAPIExporterPort")
    public RefundAPI getRefundAPIExporterPort() {
        return super.getPort(new QName("http://www.sdo.com/mas/api/refund/", "RefundAPIExporterPort"), RefundAPI.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns RefundAPI
     */
    @WebEndpoint(name = "RefundAPIExporterPort")
    public RefundAPI getRefundAPIExporterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sdo.com/mas/api/refund/", "RefundAPIExporterPort"), RefundAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REFUNDAPIEXPORTERSERVICE_EXCEPTION != null) {
            throw REFUNDAPIEXPORTERSERVICE_EXCEPTION;
        }
        return REFUNDAPIEXPORTERSERVICE_WSDL_LOCATION;
    }

}
